## Assignment: Perform SVM with PCA operation on Iris Dataset.

In [1]:
# Import required libraries
import sys, os
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import decomposition
import numpy as np
from sklearn import metrics
from sklearn.pipeline import Pipeline

In [2]:
# Load iris cancer dataset
from sklearn import datasets
dataset = datasets.load_iris()
dataset.data.shape

(150, 4)

In [3]:
# Split the dataset into train and test
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target, random_state=138)

print(X_train.shape, X_test.shape)

(112, 4) (38, 4)


In [4]:
# Performing preprocessing using PCA and output of PCA is given to the SVM as we are using Pipeline
clf = Pipeline([('pca', decomposition.PCA(n_components=3, whiten=True)),
                ('svm', svm.LinearSVC(C=1.0))])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [5]:
# Confusion matrix
print(metrics.confusion_matrix(y_pred, y_test))
plt.show()

[[15  0  0]
 [ 0 14  0]
 [ 0  2  7]]


In [6]:
# CLassification report
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.88      0.93        16
           2       0.78      1.00      0.88         7

    accuracy                           0.95        38
   macro avg       0.93      0.96      0.94        38
weighted avg       0.96      0.95      0.95        38

