In [2]:
#Create Two numpy array of size 3 X 2 and 2 X 3
import numpy as np
arr1 = np.array([[7, 2, 3],[1, 9, 5]])
arr2 = np.array([[1,7],[2, -3],[5, -10]])
print(arr1)
print(arr2)


[[7 2 3]
 [1 9 5]]
[[  1   7]
 [  2  -3]
 [  5 -10]]


In [3]:
#Randomly Initalize that array
arr = np.random.rand(2, 4)
print(arr)

[[0.01425073 0.42787503 0.85511719 0.8030986 ]
 [0.36096969 0.94055257 0.41937523 0.04506388]]


In [4]:
# perform matrix multiplication
mat_mul = np.dot(arr1, arr2)
print(mat_mul)

[[ 26  13]
 [ 44 -70]]


In [6]:
# perform element wise matrix multiplication
ans = [[0 for x in range(len(arr1))] for y in range(len(arr2[0]))]

for i in range(len(arr1)): 
  for j in range(len(arr2[0])): 
    for k in range(len(arr2)): 
      ans[i][j] += arr1[i][k] * arr2[k][j]
 
print(ans)

[[26, 13], [44, -70]]


In [7]:
# mean of first matrix
mean_arr1 = np.mean(arr1)
print(mean_arr1)

4.5


In [11]:
#Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
import pandas as pd
main_data = pd.read_csv("mtcars.csv")


In [12]:
del main_data['model']
mean_center = main_data.apply(lambda e: e - e.mean())
print(mean_center.head())

        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
