In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [5]:
# Define dataset
dataset = torch.utils.data.TensorDataset(inputs,targets)


In [6]:
# Define data loader
dataloader = torch.utils.data.DataLoader(dataset,batch_size=5)

In [7]:
# Define model
model = nn.Linear(inputs.shape[1],targets.shape[1])
model.parameters()

<generator object Module.parameters at 0x7ff9a6798850>

In [8]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=1e-4)


In [9]:
# Import nn.functional
import torch.nn.functional as F

In [10]:
# Define loss function
loss_fn = F.mse_loss

In [11]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
   for epoch in range(num_epochs):
       for xb,yb in dataloader:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(yb,pred)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
       print('Training loss: ', loss_fn(model(inputs), targets))

In [12]:

# Train the model for 100 epochs
fit(120 , model , loss_fn, optimizer)



Training loss:  tensor(948.1046, grad_fn=<MseLossBackward>)
Training loss:  tensor(422.3940, grad_fn=<MseLossBackward>)
Training loss:  tensor(242.8923, grad_fn=<MseLossBackward>)
Training loss:  tensor(164.0525, grad_fn=<MseLossBackward>)
Training loss:  tensor(120.6259, grad_fn=<MseLossBackward>)
Training loss:  tensor(93.1718, grad_fn=<MseLossBackward>)
Training loss:  tensor(74.5883, grad_fn=<MseLossBackward>)
Training loss:  tensor(61.5536, grad_fn=<MseLossBackward>)
Training loss:  tensor(52.1839, grad_fn=<MseLossBackward>)
Training loss:  tensor(45.2936, grad_fn=<MseLossBackward>)
Training loss:  tensor(40.1019, grad_fn=<MseLossBackward>)
Training loss:  tensor(36.0852, grad_fn=<MseLossBackward>)
Training loss:  tensor(32.8894, grad_fn=<MseLossBackward>)
Training loss:  tensor(30.2745, grad_fn=<MseLossBackward>)
Training loss:  tensor(28.0767, grad_fn=<MseLossBackward>)
Training loss:  tensor(26.1842, grad_fn=<MseLossBackward>)
Training loss:  tensor(24.5203, grad_fn=<MseLossBac

In [13]:
# Generate predictions
#preds = model(?)
#preds
preds = model(inputs)
preds

tensor([[ 57.2378,  70.3879],
        [ 82.0892, 100.3856],
        [118.8452, 133.4799],
        [ 21.1191,  37.1574],
        [101.7684, 118.6170],
        [ 57.2378,  70.3879],
        [ 82.0892, 100.3856],
        [118.8452, 133.4799],
        [ 21.1191,  37.1574],
        [101.7684, 118.6170],
        [ 57.2378,  70.3879],
        [ 82.0892, 100.3856],
        [118.8452, 133.4799],
        [ 21.1191,  37.1574],
        [101.7684, 118.6170]], grad_fn=<AddmmBackward>)

In [14]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(inputs,targets,test_size=0.5,random_state=140)

In [17]:
model.fit(X_train,Y_train)
predictions = model.predict(X_test)
predictions

array([[ 98.71938 , 119.30003 ],
       [119.      , 133.      ],
       [ 98.71938 , 119.30003 ],
       [ 81.      , 101.      ],
       [119.      , 133.      ],
       [ 56.000008,  70.      ],
       [ 98.71938 , 119.30003 ],
       [ 81.      , 101.      ]], dtype=float32)

In [18]:
Y_test

tensor([[103., 119.],
        [119., 133.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.],
        [ 56.,  70.],
        [103., 119.],
        [ 81., 101.]])

In [19]:
from sklearn.metrics import mean_squared_error

print(mean_squared_error(Y_test,predictions))

3.4525688


In [20]:
import tensorflow as tf

inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

X_train,X_test,Y_train,Y_test = train_test_split(inputs,targets,test_size=0.5,random_state=140)

In [21]:
model = tf.keras.Sequential()
model.compile(loss="mean_squared_error")