In [4]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [5]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [6]:
# Target (apples)
targets = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

In [7]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])

In [8]:
# Weights and biases
W = torch.rand((1,inputs.shape[1]),requires_grad=True)
print(W)

b = torch.zeros(size=(inputs.shape[0],1),requires_grad=True)
b


tensor([[0.5000, 0.8290, 0.9848]], requires_grad=True)


tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], requires_grad=True)

In [9]:
# Define the model
predict = lambda X,W,b: X@W.T+b


In [10]:
# Generate predictions
y_h = predict(inputs,W,b)
y_h

tensor([[134.3851],
        [181.4738],
        [211.6985],
        [123.0792],
        [183.0155]], grad_fn=<AddBackward0>)

In [11]:
# Compare with targets
targets


tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])

In [12]:
# MSE loss
loss_fn = torch.nn.MSELoss()
my_loss = lambda Y,Yhat : ((Y-Yhat)**2).mean()


In [13]:
# Compute loss
loss = loss_fn(targets,y_h)
loss


tensor(8290.3379, grad_fn=<MseLossBackward>)

In [14]:
# Compute gradients
loss.backward()

In [15]:
# Gradients for weights
W.grad

tensor([[15504.4561, 15417.1943,  9807.3633]])

In [16]:
# Gradients for bias
b.grad

tensor([[31.3540],
        [40.1895],
        [37.0794],
        [40.4317],
        [32.0062]])

In [17]:
W.grad.zero_(),b.grad.zero_()

(tensor([[0., 0., 0.]]), tensor([[0.],
         [0.],
         [0.],
         [0.],
         [0.]]))

In [18]:
# Generate predictions
X = torch.from_numpy( np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32'))
Y = torch.from_numpy( np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32'))

W = torch.rand((1,X.shape[1]),requires_grad=True)
b = torch.tensor([[0.0]],requires_grad=True)

predict = lambda X,W,b : X@W.T + b

W,b,W.grad,b.grad
predictions = predict(X,W,b)
predictions

tensor([[139.2955],
        [181.0685],
        [215.2868],
        [142.8614],
        [170.0016]], grad_fn=<AddBackward0>)

In [19]:
# Calculate the loss
loss = loss_fn(Y,predictions)
loss

tensor(9063.9395, grad_fn=<MseLossBackward>)

In [20]:
# Compute gradients
loss.backward()
print(W.grad,b.grad)

tensor([[16205.8945, 15567.3828,  9893.0850]]) tensor([[187.0055]])


In [21]:
# Adjust weights & reset gradients
alpha = 1e-7
with torch.no_grad():
    W -= alpha*(W.grad)
    b -= alpha*(b.grad)
W.grad.zero_(),b.grad.zero_()
W,b
predictions = predict(X,W,b)
predictions

tensor([[139.0303],
        [180.7207],
        [214.8798],
        [142.5925],
        [169.6711]], grad_fn=<AddBackward0>)

In [22]:
#print(w)
W

tensor([[0.9097, 0.8660, 0.3395]], requires_grad=True)

In [23]:
# Calculate loss

loss = loss_fn(Y,predictions)
loss

tensor(9003.7598, grad_fn=<MseLossBackward>)

In [24]:


# Train for 100 epochs
losses=[]
for i in range(100):
    yhat = predict(X,W,b)
    loss = loss_fn(Y,yhat)
    loss.backward()
    with torch.no_grad():
        W -= alpha*W.grad
        b -= alpha*b.grad
    losses.append(loss)
    W.grad.zero_(),b.grad.zero_()



In [25]:
# Calculate loss
loss_fn(Y,yhat)

tensor(4749.7515, grad_fn=<MseLossBackward>)

In [26]:
# Print predictions
predict(X,W,b)

tensor([[116.7743],
        [151.5384],
        [180.7931],
        [119.9510],
        [141.9818]], grad_fn=<AddBackward0>)

In [27]:
# Print targets
Y

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])